import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <svg width="33" height="32" viewBox="0 0 33 32" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fillRule="evenodd" clipRule="evenodd" d="M33 0L5 0L16 16L33 0Z" fill="#0019BF" fillOpacity="0.7"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M5 0L0 32H32L5 0Z" fill="#0019BF"/>
      </svg>


        <h1 className={styles.title_lead}>
          Design, product craft &amp; leadership in both
        </h1>

        <div className={styles.container}>
          <div className={styles.col_photo}>
            <Image 
              src="/us.jpg" 
              alt="Vercel Logo" 
              layout="intrinsic"
              width={736}
              height={982}
            />
          </div>

          <div className={styles.col_spacer}>
            
          </div>

          <div className={styles.col_content}>
            <p>
              Hi there! I&apos;m Kish — a Designer, Design Leader and wannabe Software Engineer born, raised and based in London, UK. 
            </p>

            <p>
              I’m currently building a new investment brokerage in Europe called Lightyear with a ridiculously talented group of people — one without all the unnecessary fees and barriers and that actually helps its customers become better investors. Check out my Lightyear profile here.
            </p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <small>
        You can find me in other places on the internet, such as Twitter, Figma, Github or LinkedIn. Alternatively, reach out to me directly at contact@kishpatel.com.
        </small>
      </footer>
    </div>
  )
}

export default Home
